# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('is_true', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_subject', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='www.Person')),
                ('type_person', models.CharField(default=b'admin', max_length=250)),
            ],
            bases=('www.person',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='www.Person')),
                ('type_person', models.CharField(default=b'professor', max_length=250)),
            ],
            bases=('www.person',),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Quiz'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Question'),
        ),
        migrations.AddField(
            model_name='archive',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Choice'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='www.User')),
            ],
            bases=('www.user',),
        ),
        migrations.AddField(
            model_name='archive',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.User'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Professor'),
        ),
        migrations.AlterUniqueTogether(
            name='archive',
            unique_together=set([('choice', 'person')]),
        ),
    ]
